#!/usr/bin/env sh
###             _   _     _      _         
###  __ _  ___ | |_| |__ | | ___| |_ _   _ 
### / _` |/ _ \| __| '_ \| |/ _ \ __| | | |
###| (_| | (_) | |_| |_) | |  __/ |_| |_| |
### \__, |\___/ \__|_.__/|_|\___|\__|\__,_|
### |___/                                  
###       https://www.youtube.com/user/gotbletu
###       https://twitter.com/gotbletu
###       https://github.com/gotbletu
###       gotbletu@gmail.com
###
### Author          : gotbletu
### Name            : diana-progress
### Version         : 0.2.1
### Date            : 2020-05-05
### Description     : outputs basic stats and info about the current aria2c daemon downloads
### Depends On      : diana (https://github.com/baskerville/diana)
### Video Demo      : https://www.youtube.com/watch?v=y59JwlYsrAE

# printf '%s\n' "====BANDWIDTH===="
diana stats
printf '%s\n' "=====ACTIVE======"
diana list
printf '%s\n' "=====PAUSED======"
diana paused
printf '%s\n' "====COMPLETED===="
diana stopped
printf '%s\n' "=====ERRORS======"
diana errors
