#!/usr/bin/env bash
###             _   _     _      _         
###  __ _  ___ | |_| |__ | | ___| |_ _   _ 
### / _` |/ _ \| __| '_ \| |/ _ \ __| | | |
###| (_| | (_) | |_| |_) | |  __/ |_| |_| |
### \__, |\___/ \__|_.__/|_|\___|\__|\__,_|
### |___/                                  
###       https://www.youtube.com/user/gotbletu
###       https://twitter.com/gotbletu
###       https://github.com/gotbletu
###       gotbletu@gmail.com
###
### Author          : gotbletu
### Name            : diana-progress
### Version         : 0.2
### Date            : 20190607
### Description     : outputs basic stats and info about the current aria2c daemon downloads
### Depends On      : bash  diana (https://github.com/baskerville/diana)
### Video Demo      : https://www.youtube.com/watch?v=y59JwlYsrAE

DIANA_BIN=/usr/bin/diana

# printf '%s\n' "====BANDWIDTH===="
"$DIANA_BIN" stats
printf '%s\n' "=====ACTIVE======"
"$DIANA_BIN" list
printf '%s\n' "=====PAUSED======"
"$DIANA_BIN" paused
printf '%s\n' "====COMPLETED===="
"$DIANA_BIN" stopped
printf '%s\n' "=====ERRORS======"
"$DIANA_BIN" errors
